export interface Player {
    profile_id: number,
    steam_id: string,
    name: string,
    clan: string,
    country: string,
    slot: number,
    slot_type: number,
    rating: number,
    rating_change: number | null,
    games: number,
    wins: number,
    streak: number,
    drops: number,
    color: number | null,
    team: number | null,
    civ: number | null,
    civ_alpha: number | null,
    won: boolean | null,
}